---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: archspec-feature-discovery
  namespace: archspec-feature-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: archspec-feature-discovery
subjects:
- kind: ServiceAccount
  name: archspec-feature-discovery
  namespace: archspec-feature-discovery
# userNames:
# - system:serviceaccount:archspec-feature-discovery:archspec-feature-discovery
